package TacticusDataHandling;

import java.util.HashMap;
import java.util.Map;

/**
 * HeroDetail class fetches all the necessary info of the hero data and contains a hashmap of more commonly used names to replace the original data.
 */
public class HeroDetail {
    // Heroes own specific name in the JSON file
    private String unitId;

    // Heroes own power level in the JSON file - Unused for now
    private int power;

    // Returns unitId for further use
    public String getUnitId() { return unitId; }

    // Unused for now
    public int getPower() { return power; }

    // HashMap contains the unit names from the API data and sets a more used name for them.
    public static final Map<String, String> heroIdToName = new HashMap<>();

    static {
        heroIdToName.put("ultraTigurius", "Tigurius");
        heroIdToName.put("ultraInceptorSgt", "Bellator");
        heroIdToName.put("ultraEliminatorSgt", "Certus");
        heroIdToName.put("adeptRetributor", "Vindicta");
        heroIdToName.put("ultraApothecary", "Incisus");
        heroIdToName.put("necroWarden", "Makhotep");
        heroIdToName.put("deathBlightlord", "Maladus");
        heroIdToName.put("adeptHospitaller", "Isabella");
        heroIdToName.put("deathRotbone", "Rotbone");
        heroIdToName.put("orksWarboss", "Boss Gulgortz");
        heroIdToName.put("admecDominus", "Vitruvius");
        heroIdToName.put("admecRuststalker", "Exitor-Rho");
        heroIdToName.put("tauAunShi", "Aun'Shi");
        heroIdToName.put("admecMarshall", "Tan Gi'da");
        heroIdToName.put("worldKharn", "Kharn");
        heroIdToName.put("tauCrisis", "Re'vas");
        heroIdToName.put("orksRuntherd", "Snotflogga");
        heroIdToName.put("spaceBlackmane", "Ragnar");
        heroIdToName.put("spaceWolfPriest", "Baldr");
        heroIdToName.put("emperFlawlessBlade", "Hascule");
        heroIdToName.put("emperExultant", "Laviscus");
        heroIdToName.put("tauFarsight", "Farsight");
        heroIdToName.put("custoTrajann", "Trajann");
        heroIdToName.put("custoKyrus", "Tyrith");
        heroIdToName.put("bloodDante", "Dante");
        heroIdToName.put("emperKakophonist", "Adamatar");
        heroIdToName.put("genesPatriarch", "The Patermine");
        heroIdToName.put("emperNoiseMarine", "Shiron");
        heroIdToName.put("astraDreir", "Dreir");
        heroIdToName.put("custoAtlacoya", "Atlacoya");
        heroIdToName.put("adeptExorcist", "Exorcist");
        heroIdToName.put("bloodMephiston", "Mephiston");
        heroIdToName.put("custoBladeChampion", "Kariyan");
        heroIdToName.put("custoVexilusPraetor", "Aesoth");
        heroIdToName.put("darkaCompanion", "Forcas");
        heroIdToName.put("worldExecutions", "Tarvakh");
        heroIdToName.put("admecDestroyer", "Sy-gex");
        heroIdToName.put("genesKelermorph", "Judh");
        heroIdToName.put("genesPrimus", "Isaak");
        heroIdToName.put("bloodSanguinary", "Nicodemus");
        heroIdToName.put("tyranParasite", "Parasite");
        heroIdToName.put("genesBiophagus", "Hollan");
        heroIdToName.put("genesMagus", "Xybia");
        heroIdToName.put("bloodIntercessor", "Mataneo");
        heroIdToName.put("tyranBiovore", "Biovore");
        heroIdToName.put("bloodDeathCompany", "Lucien");
        heroIdToName.put("ultraTitus", "Titus");
        heroIdToName.put("darkaTerminator", "Baraqiel");
        heroIdToName.put("worldEightbound", "Azkor");
        heroIdToName.put("worldJakhal", "Macer");
        heroIdToName.put("tauShadowsun", "Shadowsun");
        heroIdToName.put("darkaAsmodai", "Asmodai");
        heroIdToName.put("adeptMorvenn", "Morvenn Vahl");
        heroIdToName.put("worldTerminator", "Wrask");
        heroIdToName.put("astraCreed", "Creed");
        heroIdToName.put("tyranDeathleaper", "Deathleaper");
        heroIdToName.put("darkaAzrael", "Azrael");
        heroIdToName.put("adeptCelestine", "Celestine");
        heroIdToName.put("spaceHound", "Tjark");
        heroIdToName.put("spaceStormcaller", "Njal");
        heroIdToName.put("templChampion", "Jaeger");
        heroIdToName.put("tyranWingedPrime", "Winged Prime");
        heroIdToName.put("adeptCanoness", "Roswitha");
        heroIdToName.put("templAncient", "Thoread");
        heroIdToName.put("darkaHellblaster", "Sarquael");
        heroIdToName.put("templSwordBrother", "Godswyl");
        heroIdToName.put("admecManipulus", "Actus");
        heroIdToName.put("templAggressor", "Burchard");
        heroIdToName.put("astraOrdnance", "Thaddeus");
        heroIdToName.put("eldarMauganRa", "Maugan Ra");
        heroIdToName.put("blackAbaddon", "Abaddon");
        heroIdToName.put("necroOverlord", "Anuphet");
        heroIdToName.put("eldarJainZar", "Jain Zar");
        heroIdToName.put("astraPrimarisPsy", "Sibyll");
        heroIdToName.put("templHelbrecht", "Helbrecht");
        heroIdToName.put("ultraCalgar", "Calgar");
        heroIdToName.put("thousTzaangor", "Yazaghor");
        heroIdToName.put("thousTerminator", "Toth");
        heroIdToName.put("thousInfernalMaster", "Abraxas");
        heroIdToName.put("thousSorcerer", "Thaumachus");
        heroIdToName.put("thousAhriman", "Ahriman");
        heroIdToName.put("deathBlightbringer", "Corrodius");
        heroIdToName.put("astraBullgryn", "Kut");
        heroIdToName.put("tyranNeurothrope", "Neurothrope");
        heroIdToName.put("deathPutrifier", "Pestillian");
        heroIdToName.put("orksNob", "Tanksmasha");
        heroIdToName.put("spaceRockfist", "Arjac");
        heroIdToName.put("spaceWulfen", "Ulf");
        heroIdToName.put("necroPlasmancer", "Thutmose");
        heroIdToName.put("blackPossession", "Archimatos");
        heroIdToName.put("blackTerminator", "Angrax");
        heroIdToName.put("tyranTyrantGuard", "Tyrant");
        heroIdToName.put("astraYarrick", "Yarrick");
        heroIdToName.put("deathTyphus", "Typhus");
        heroIdToName.put("necroSpyder", "Aleph-Null");
        heroIdToName.put("orksKillaKan", "Snappawrecka");
        heroIdToName.put("tauMarksman", "Sho'syl");
        heroIdToName.put("tauDarkstrider", "Darkstrider");
        heroIdToName.put("blackObliterator", "Volk");
        heroIdToName.put("eldarRanger", "Calandis");
        heroIdToName.put("eldarFarseer", "Eldryon");
        heroIdToName.put("orksBigMek", "Gibbascrapz");
        heroIdToName.put("eldarAutarch", "Aethana");
        heroIdToName.put("necroDestroyer", "Imospekh");
        heroIdToName.put("blackHaarken", "Haarken");
        heroIdToName.put("", "");
    }

    public static final Map<String, String> heroIdToEmoji = new HashMap<>();

    static {
        heroIdToEmoji.put("ultraTigurius", "<:C_UM_Varro:1478863255525920919>");
        heroIdToEmoji.put("ultraInceptorSgt", "<:C_UM_Bellator:1478863901562109972>");
        heroIdToEmoji.put("ultraEliminatorSgt", "<:C_UM_Certus:1168971514020892672>");
        heroIdToEmoji.put("adeptRetributor", "<:C_SB_Vindicta:1478863282524786830>");
        heroIdToEmoji.put("ultraApothecary", "<:C_UM_Incisus:1478863758540668960>");
        heroIdToEmoji.put("necroWarden", "<:C_N_Makhotep:1478862949710958703>");
        heroIdToEmoji.put("deathBlightlord", "<:C_DG_Maladus:1478879655963398346>");
        heroIdToEmoji.put("adeptHospitaller", "<:C_SB_Isabella:1478863733919977614>");
        heroIdToEmoji.put("deathRotbone", "<:C_DG_Rotbone:1478864119548612820>");
        heroIdToEmoji.put("orksWarboss", "<:C_O_BossGulgortz:1478832865583173923>");
        heroIdToEmoji.put("admecDominus", "<:C_AD_Vitruvius:1478832927084380323>");
        heroIdToEmoji.put("admecRuststalker", "<:C_AD_Rho:1478834828597006399>");
        heroIdToEmoji.put("tauAunShi", "<:C_Ta_AunShi:1478832800743559178>");
        heroIdToEmoji.put("admecMarshall", "<:C_AD_Tangida:1478833035708334272>");
        heroIdToEmoji.put("worldKharn", "<:C_WE_Kharn:1478836058417402067>");
        heroIdToEmoji.put("tauCrisis", "<:C_Ta_Revas:1478830175721357435>");
        heroIdToEmoji.put("orksRuntherd", "<:C_O_Snotflogga:1478862780881702972>");
        heroIdToEmoji.put("spaceBlackmane", "<:C_SW_Ragnar:1478834536254144532>");
        heroIdToEmoji.put("spaceWolfPriest", "<:C_SW_Baldr:1478863929903157369>");
        heroIdToEmoji.put("emperFlawlessBlade", "<:C_EC_Hascule:1478879761865506948>");
        heroIdToEmoji.put("emperExultant", "<:C_EC_Laviscus:1478830835267403847>");
        heroIdToEmoji.put("tauFarsight", "<:C_Ta_Farsight:1478832731407257680>");
        heroIdToEmoji.put("custoTrajann", "<:C_AC_Leader:1478832979005538466>");
        heroIdToEmoji.put("custoKyrus", "<:C_AC_Tyrith:1478863312723644546>");
        heroIdToEmoji.put("bloodDante", "<:C_BA_Dante:1478834878488252566>");
        heroIdToEmoji.put("emperKakophonist", "<:C_EC_Adamatar:1478879913158250691>");
        heroIdToEmoji.put("genesPatriarch", "<:C_GSC_Patermine:1478862647427469405>");
        heroIdToEmoji.put("emperNoiseMarine", "<:C_EC_Shiron:1478864091291451606>");
        heroIdToEmoji.put("astraDreir", "<:C_AM_Dreir:1478863675506032805>");
        heroIdToEmoji.put("custoAtlacoya", "<:C_AC_Atlacoya:1478834924776853555>");
        heroIdToEmoji.put("bloodMephiston", "<:C_BA_mephiston:1478834585642205376>");
        heroIdToEmoji.put("custoBladeChampion", "<:C_AC_SwordMaster:1478834642781077636>");
        heroIdToEmoji.put("custoVexilusPraetor", "<:C_AC_Aesoth:1478835836056240230>");
        heroIdToEmoji.put("darkaCompanion", "<:C_DA_forcas:1478834700629049525>");
        heroIdToEmoji.put("worldExecutions", "<:C_WE_Tarvakh:1478864060736081932>");
        heroIdToEmoji.put("admecDestroyer", "<:C_AD_SYGEX:1478863436388503654>");
        heroIdToEmoji.put("genesKelermorph", "<:C_GSC_Judh:1478862884531339314>");
        heroIdToEmoji.put("genesPrimus", "<:C_GSC_Isaak:1478863016543125636>");
        heroIdToEmoji.put("bloodSanguinary", "<:C_BA_Nicodemus:1478863589702893750>");
        heroIdToEmoji.put("genesMagus", "<:C_GS_Xybia:1478830889759670314>");
        heroIdToEmoji.put("bloodIntercessor", "<:C_BA_Mattaneo:1478863649161482433>");
        heroIdToEmoji.put("bloodDeathCompany", "<:C_BA_Lucien:1478863708754022535>");
        heroIdToEmoji.put("ultraTitus", "<:C_UM_titus:1478863405296390327>");
        heroIdToEmoji.put("worldEightbound", "<:C_WE_Azkor:1478879823039434902>");
        heroIdToEmoji.put("worldJakhal", "<:C_WE_Macer:1478879568004911309>");
        heroIdToEmoji.put("tauShadowsun", "<:C_Ta_Shadowsun:1478863102748524654>");
        heroIdToEmoji.put("darkaAsmodai", "<:C_DA_asmodai:1478834969521553622>");
        heroIdToEmoji.put("adeptMorvenn", "<:C_SB_MorvennVahl:1478863620262723666>");
        heroIdToEmoji.put("darkaAzrael", "<:C_DA_Azrael:1478863953546186833>");
        heroIdToEmoji.put("adeptCelestine", "<:CE_SB_Celestine:1478863811804004492>");
        heroIdToEmoji.put("templChampion", "<:C_DA_BrotherJaeger:1478863838999875821>");
        heroIdToEmoji.put("tyranWingedPrime", "<:C_T_WingedPrime:1478830216116965598>");
        heroIdToEmoji.put("adeptCanoness", "<:C_SB_Roswitha:1478833086711070902>");
        heroIdToEmoji.put("templAncient", "<:C_BT_AncientThoread:1478863978179465340>");
        heroIdToEmoji.put("darkaHellblaster", "<:C_DA_Sarquael:1478863488934871263>");
        heroIdToEmoji.put("templSwordBrother", "<:C_BT_SwordBrotherGodswyl:1478863463857127474>");
        heroIdToEmoji.put("admecManipulus", "<:C_AD_Actus:1478835886232961155>");
        heroIdToEmoji.put("astraOrdnance", "<:C_AM_ThaddeusNoble:1478863378876334131>");
        heroIdToEmoji.put("eldarMauganRa", "<:C_E_MauganRa:1478862752046121087>");
        heroIdToEmoji.put("blackAbaddon", "<:C_BL_Abaddon:1478830299306659992>");
        heroIdToEmoji.put("necroOverlord", "<:C_N_Anuphet:1478863182012485723>");
        heroIdToEmoji.put("eldarJainZar", "<:C_E_JainZar:1478862986004140042>");
        heroIdToEmoji.put("astraPrimarisPsy", "<:C_AM_SibyllDevine:1478863518227890338>");
        heroIdToEmoji.put("templHelbrecht", "<:C_BT_HighMarshalHelbrecht:1478834776134778983>");
        heroIdToEmoji.put("ultraCalgar", "<:C_UM_MarneusCalgar:1478834476350967910>");
        heroIdToEmoji.put("thousTzaangor", "<:C_Ts_Yazaghor:1478835957351317627>");
        heroIdToEmoji.put("thousInfernalMaster", "<:C_Ts_Abraxas:1478836193490894948>");
        heroIdToEmoji.put("thousSorcerer", "<:C_Ts_Thaumachus:1478836011998904320>");
        heroIdToEmoji.put("thousAhriman", "<:C_Ts_Ahriman:1478836151463968850>");
        heroIdToEmoji.put("deathBlightbringer", "<:C_DG_Corrodius:1478879790911197377>");
        heroIdToEmoji.put("tyranNeurothrope", "<:C_T_Neurothrope:1478830256126169356>");
        heroIdToEmoji.put("deathPutrifier", "<:C_DG_Pestillian:1478864151752474838>");
        heroIdToEmoji.put("orksNob", "<:C_O_Tanksmasha:1478862675747541152>");
        heroIdToEmoji.put("spaceWulfen", "<:C_SW_Ulf:1478863348119633970>");
        heroIdToEmoji.put("necroPlasmancer", "<:C_N_Thutmose:1478862612564414515>");
        heroIdToEmoji.put("blackPossession", "<:C_BL_Archimatos:1478836108379820193>");
        heroIdToEmoji.put("astraYarrick", "<:C_AM_Yarrik:1478863785736405133>");
        heroIdToEmoji.put("deathTyphus", "<:C_DG_Typhus:1478864004850913462>");
        heroIdToEmoji.put("necroSpyder", "<:C_N_Aleph:1478832674478100691>");
        heroIdToEmoji.put("orksKillaKan", "<:C_O_Snappawrecka:1478862719305253005>");
        heroIdToEmoji.put("tauMarksman", "<:C_Ta_Shosyl:1478830960609984716>");
        heroIdToEmoji.put("tauDarkstrider", "<:C_Ta_Darkstrider:1478832561286414570>");
        heroIdToEmoji.put("blackObliterator", "<:C_BL_Volk:1478864030557798581>");
        heroIdToEmoji.put("eldarFarseer", "<:C_E_Eldyron:1478832623915630777>");
        heroIdToEmoji.put("orksBigMek", "<:C_O_Gibbascrapz:1478863077259743383>");
        heroIdToEmoji.put("eldarAutarch", "<:C_E_Aethana:1478863153654923435>");
        heroIdToEmoji.put("necroDestroyer", "<:C_N_Imospekh:1478863047031394356>");
        heroIdToEmoji.put("blackHaarken", "<:C_BL_HaarkenWorldclaimer:1478879531115872297>");
        heroIdToEmoji.put("", "");

        heroIdToEmoji.put("eldarRanger", "Calandis");
        heroIdToEmoji.put("blackTerminator", "Angrax");
        heroIdToEmoji.put("tyranTyrantGuard", "Tyrant");
        heroIdToEmoji.put("spaceRockfist", "Arjac");
        heroIdToEmoji.put("astraBullgryn", "Kut");
        heroIdToEmoji.put("thousTerminator", "Toth");
        heroIdToEmoji.put("templAggressor", "Burchard");
        heroIdToEmoji.put("spaceHound", "Tjark");
        heroIdToEmoji.put("spaceStormcaller", "Njal");
        heroIdToEmoji.put("worldTerminator", "Wrask");
        heroIdToEmoji.put("astraCreed", "Creed");
        heroIdToEmoji.put("tyranDeathleaper", "Deathleaper");
        heroIdToEmoji.put("darkaTerminator", "Baraqiel");
        heroIdToEmoji.put("tyranParasite", "Parasite");
        heroIdToEmoji.put("genesBiophagus", "Hollan");
    }

    // On progress, unused for now.
    public static final Map<String, String> heroIdToImageUrl = new HashMap<>();

    static {
        heroIdToImageUrl.put("ultraTigurius","https://tacticus.wiki.gg/images/Varro_Tigurius_Icon_Large.png?fe76be=&format=original");
        heroIdToImageUrl.put("ultraInceptorSgt", "Bellator");
        heroIdToImageUrl.put("ultraEliminatorSgt", "Certus");
        heroIdToImageUrl.put("adeptRetributor", "Vindicta");
        heroIdToImageUrl.put("ultraApothecary", "Incisus");
        heroIdToImageUrl.put("necroWarden", "Makhotep");
        heroIdToImageUrl.put("deathBlightlord", "Maladus");
        heroIdToImageUrl.put("adeptHospitaller", "Isabella");
        heroIdToImageUrl.put("deathRotbone", "Rotbone");
        heroIdToImageUrl.put("orksWarboss", "Boss Gulgortz");
        heroIdToImageUrl.put("admecDominus", "Vitruvius");
        heroIdToImageUrl.put("admecRuststalker", "Exitor-Rho");
        heroIdToImageUrl.put("tauAunShi", "https://tacticus.wiki.gg/images/Aun%27Shi_Icon_Large.png?7fbdf6=&format=original");
        heroIdToImageUrl.put("admecMarshall", "Tan Gi'da");
        heroIdToImageUrl.put("worldKharn", "https://tacticus.wiki.gg/images/Kharn_Icon_Large.png?c055be=&format=original");
        heroIdToImageUrl.put("tauCrisis", "Re'vas");
        heroIdToImageUrl.put("orksRuntherd", "https://tacticus.wiki.gg/images/Snotflogga_Icon_Large.png?5e2e82=&format=original");
        heroIdToImageUrl.put("spaceBlackmane", "https://tacticus.wiki.gg/images/Ragnar_Icon_Large.png?1aa7e4=&format=original");
        heroIdToImageUrl.put("thousDaemonPrince", "Z'Kar");
        heroIdToImageUrl.put("spaceWolfPriest", "Baldr");
        heroIdToImageUrl.put("emperFlawlessBlade", "Hascule");
        heroIdToImageUrl.put("emperExultant", "https://tacticus.wiki.gg/images/Laviscus_Icon_Large.png?2a3bd0=&format=original");
        heroIdToImageUrl.put("tauFarsight", "Farsight");
        heroIdToImageUrl.put("custoTrajann", "Trajann");
        heroIdToImageUrl.put("custoKyrus", "Tyrith");
        heroIdToImageUrl.put("bloodDante", "https://tacticus.wiki.gg/images/Dante_Icon_Large.png?cec05d=&format=original");
        heroIdToImageUrl.put("emperKakophonist", "Adamatar");
        heroIdToImageUrl.put("genesPatriarch", "The Patermine");
        heroIdToImageUrl.put("orksRukkatrukk", "Rukkatrukk");
        heroIdToImageUrl.put("emperNoiseMarine", "Shiron");
        heroIdToImageUrl.put("astraDreir", "Dreir");
        heroIdToImageUrl.put("custoAtlacoya", "Atlacoya");
        heroIdToImageUrl.put("adeptExorcist", "Exorcist");
        heroIdToImageUrl.put("bloodMephiston", "Mephiston");
        heroIdToImageUrl.put("custoBladeChampion", "https://tacticus.wiki.gg/images/Kariyan_Icon_Large.png?dbfc24=&format=original");
        heroIdToImageUrl.put("custoVexilusPraetor", "Aesoth");
        heroIdToImageUrl.put("darkaCompanion", "Forcas");
        heroIdToImageUrl.put("worldExecutions", "Tarvakh");
        heroIdToImageUrl.put("admecDestroyer", "Sy-gex");
        heroIdToImageUrl.put("genesKelermorph", "Judh");
        heroIdToImageUrl.put("genesPrimus", "Isaak");
        heroIdToImageUrl.put("bloodSanguinary", "Nicodemus");
        heroIdToImageUrl.put("tyranParasite", "Parasite");
        heroIdToImageUrl.put("genesBiophagus", "Hollan");
        heroIdToImageUrl.put("genesMagus", "Xybia");
        heroIdToImageUrl.put("bloodIntercessor", "Mataneo");
        heroIdToImageUrl.put("tyranBiovore", "Biovore");
        heroIdToImageUrl.put("bloodDeathCompany", "Lucien");
        heroIdToImageUrl.put("ultraTitus", "Titus");
        heroIdToImageUrl.put("darkaTerminator", "Baraqiel");
        heroIdToImageUrl.put("worldEightbound", "Azkor");
        heroIdToImageUrl.put("worldJakhal", "Macer");
        heroIdToImageUrl.put("tauShadowsun", "Shadowsun");
        heroIdToImageUrl.put("darkaAsmodai", "Asmodai");
        heroIdToImageUrl.put("adeptMorvenn", "Morvenn Vahl");
        heroIdToImageUrl.put("worldTerminator", "Wrask");
        heroIdToImageUrl.put("astraCreed", "Creed");
        heroIdToImageUrl.put("tyranDeathleaper", "Deathleaper");
        heroIdToImageUrl.put("darkaAzrael", "Azrael");
        heroIdToImageUrl.put("adeptCelestine", "Celestine");
        heroIdToImageUrl.put("spaceHound", "Tjark");
        heroIdToImageUrl.put("spaceStormcaller", "Njal");
        heroIdToImageUrl.put("templChampion", "Jaeger");
        heroIdToImageUrl.put("tyranWingedPrime", "Winged Prime");
        heroIdToImageUrl.put("adeptCanoness", "Roswitha");
        heroIdToImageUrl.put("templAncient", "Thoread");
        heroIdToImageUrl.put("darkaHellblaster", "Sarquael");
        heroIdToImageUrl.put("templSwordBrother", "Godswyl");
        heroIdToImageUrl.put("admecManipulus", "Actus");
        heroIdToImageUrl.put("templAggressor", "Burchard");
        heroIdToImageUrl.put("astraOrdnance", "Thaddeus");
        heroIdToImageUrl.put("eldarMauganRa", "Maugan Ra");
        heroIdToImageUrl.put("blackAbaddon", "Abaddon");
        heroIdToImageUrl.put("necroOverlord", "Anuphet");
        heroIdToImageUrl.put("eldarJainZar", "Jain Zar");
        heroIdToImageUrl.put("astraPrimarisPsy", "Sibyll");
        heroIdToImageUrl.put("templHelbrecht", "Helbrecht");
        heroIdToImageUrl.put("ultraCalgar", "https://tacticus.wiki.gg/images/Marneus_Calgar_Icon_Large.png?a3da4f=&format=original");
        heroIdToImageUrl.put("thousTzaangor", "Yazaghor");
        heroIdToImageUrl.put("thousTerminator", "Toth");
        heroIdToImageUrl.put("thousInfernalMaster", "Abraxas");
        heroIdToImageUrl.put("thousSorcerer", "Thaumachus");
        heroIdToImageUrl.put("thousAhriman", "Ahriman");
        heroIdToImageUrl.put("deathBlightbringer", "Corrodius");
        heroIdToImageUrl.put("astraBullgryn", "Kut");
        heroIdToImageUrl.put("tyranNeurothrope", "Neurothrope");
        heroIdToImageUrl.put("deathPutrifier", "Pestillian");
        heroIdToImageUrl.put("orksNob", "Tanksmasha");
        heroIdToImageUrl.put("spaceRockfist", "Arjac");
        heroIdToImageUrl.put("spaceWulfen", "Ulf");
        heroIdToImageUrl.put("necroPlasmancer", "Thutmose");
        heroIdToImageUrl.put("blackPossession", "Archimatos");
        heroIdToImageUrl.put("blackTerminator", "Angrax");
        heroIdToImageUrl.put("tyranTyrantGuard", "Tyrant");
        heroIdToImageUrl.put("astraYarrick", "Yarrick");
        heroIdToImageUrl.put("deathTyphus", "Typhus");
        heroIdToImageUrl.put("necroSpyder", "Aleph-Null");
        heroIdToImageUrl.put("orksKillaKan", "Snappawrecka");
        heroIdToImageUrl.put("tauMarksman", "Sho'syl");
        heroIdToImageUrl.put("tauDarkstrider", "Darkstrider");
        heroIdToImageUrl.put("blackObliterator", "Volk");
        heroIdToImageUrl.put("eldarRanger", "Calandis");
        heroIdToImageUrl.put("eldarFarseer", "https://tacticus.wiki.gg/images/Eldryon_Icon_Large.png?271d3f=&format=original");
        heroIdToImageUrl.put("orksBigMek", "Gibbascrapz");
        heroIdToImageUrl.put("eldarAutarch", "Aethana");
        heroIdToImageUrl.put("necroDestroyer", "Imospekh");
        heroIdToImageUrl.put("blackHaarken", "Haarken");
        heroIdToImageUrl.put("", "");
    }
}
